# Generated by Django 3.2.3 on 2021-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='marca do produto')),
                ('image', models.ImageField(upload_to='marca', verbose_name='imagem do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='categoria do produto')),
                ('image', models.ImageField(upload_to='categoria', verbose_name='imagem do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tamanho do produto')),
                ('image', models.ImageField(upload_to='tamanho', verbose_name='imagem do produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
