# Generated by Django 3.2.3 on 2021-11-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='dadosBrand', verbose_name='imagem do produto'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='dadosCategory', verbose_name='imagem do produto'),
        ),
    ]
