# Generated by Django 3.2.3 on 2021-11-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20211126_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='ecommerce/cofre/dadosBrand', verbose_name='imagem do produto'),
        ),
    ]
