# Generated by Django 3.2.3 on 2021-11-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='ecommerce/cofre/dadosCategory', verbose_name='imagem do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='ecommerce/cofre/dadosProduct'),
        ),
    ]
