# Generated by Django 3.2.3 on 2021-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20211126_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='ecommerce/media/dadosBrand', verbose_name='imagem do produto'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='ecommerce/media/dadosCategory', verbose_name='imagem do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='ecommerce/media/dadosProduct'),
        ),
    ]
