# Generated by Django 3.2.3 on 2021-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20211127_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/dadosCategory', verbose_name='imagem do produto'),
        ),
    ]
