# Generated by Django 3.2.3 on 2021-11-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20211128_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banner'},
        ),
    ]
