# Generated by Django 3.2.3 on 2021-12-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_product_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '3.Marcas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1.Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2.Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '5.Atributos do Produto'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4.Tamanhos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='visivel na pagina principal'),
        ),
    ]
