# Generated by Django 3.2.3 on 2021-12-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20211201_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4.Peso'},
        ),
    ]
