# Generated by Django 3.2.3 on 2021-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20211202_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(default=1, upload_to='dadosProduct/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Preço'),
        ),
    ]
