# Generated by Django 3.2.3 on 2021-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20211214_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
