# Generated by Django 3.2.3 on 2021-12-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20211219_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2.Produtos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
