# Generated by Django 3.2.3 on 2021-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20211208_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='price',
            field=models.CharField(default=(120, 0), max_length=100, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
