# Generated by Django 3.2.3 on 2021-12-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20211208_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(default=1, upload_to='dadosProduct/'),
            preserve_default=False,
        ),
    ]
