# Generated by Django 3.2.3 on 2021-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='task',
            name='login',
            field=models.CharField(max_length=100, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='task',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
