# Generated by Django 3.2.3 on 2021-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211110_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='login',
        ),
        migrations.RemoveField(
            model_name='task',
            name='password',
        ),
        migrations.AddField(
            model_name='task',
            name='animal_race',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro'), ('passaro', 'Passaro')], default=1, max_length=50, verbose_name='Tipo de animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, default=False, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.CharField(default=False, max_length=11, verbose_name='Telefone'),
        ),
    ]
