# Generated by Django 3.2.3 on 2021-11-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211121_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='animal_race',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro'), ('passaro', 'Passaro'), ('hamster', 'Hamster'), ('peixe', 'Peixe'), ('coelho', 'Coelho'), ('porquinho_da_índia', 'Porquinho_da_índia')], max_length=100, verbose_name='Tipo de animal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de agendamento'),
        ),
    ]
