# Generated by Django 3.2.3 on 2021-11-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211115_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='problem',
            field=models.IntegerField(default=1, verbose_name='sintoma do animal'),
            preserve_default=False,
        ),
    ]
