# Generated by Django 3.2.3 on 2021-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='problem',
            field=models.CharField(max_length=100, verbose_name='sintoma do animal'),
        ),
    ]
