# Generated by Django 3.2.3 on 2021-11-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_animal_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appointment_date',
            field=models.DateField(verbose_name='data de agendamento'),
        ),
    ]
