# Generated by Django 3.2.3 on 2021-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cpf',
            field=models.CharField(default=1, max_length=11, verbose_name='digite seu cpf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='appointment_date',
            field=models.DateField(verbose_name='data de agendamento (mm/dd/2021)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do animal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
