# Generated by Django 3.2.3 on 2021-11-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20211116_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=1, verbose_name='data e hora do agendamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('finalizado', 'Finalizado')], max_length=15),
        ),
    ]
