# Generated by Django 3.2.3 on 2021-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211124_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00')], max_length=5, verbose_name='horario do agendamento'),
        ),
    ]
