# Generated by Django 3.2.3 on 2021-11-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
