# Generated by Django 3.2.3 on 2021-11-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_delete_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Dados do usuario'},
        ),
    ]
