# Generated by Django 3.2.3 on 2021-11-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Cadastros dos Usuarios'},
        ),
    ]
