# Generated by Django 3.2.3 on 2021-12-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task_list',
        ),
    ]
