# Generated by Django 3.2.3 on 2021-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20211219_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Cadastros dos Usuarios'},
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
