# Generated by Django 3.2.3 on 2021-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20211219_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
